#!/bin/bash
host1=192.168.0.2
dest1=backup/host1 #destination
logdest=backup
destM=( "$dest1" )
hostM=( "$host1" )
echo "Backup date: $(date)" >> $logdest/logfile.txt
for (( i=0; i<1; i++ ))
if rsh ${hostM[$i]} test -d $1
         then scp ${hostM[$i]}:$(dirname $1)/temp.tar ${destM[$i]}
          if [ "$(md5sum temp.tar | cut -f1 -d' ')" = "$(rsh ${hostM[$i]} md5sum $(dirname $1)/temp.tar | cut -f1 -d' ')" ]
          then tar fxP temp.tar -C ${destM[$i]}/$(basename $1)
       fi
       
